logger:
  app_name: my-app
  level:
    base: TRACE
  handlers:
    all_file_handler:
      enabled: true
    err_file_handler:
      enabled: true
    all_json_handler:
      enabled: true
    err_json_handler:
      enabled: true
